<a href="https://colab.research.google.com/github/roneljr/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Midterm Exam

#Question 1. Create a Python code that displays a square matrix whose length is 5

In [3]:
import numpy as np 
A = np.array ([[1,2,3,4,5],[2,0,0,0,0],[3,0,0,0,0],[4,0,0,0,0],[5,0,0,0,0]]) #5x5 matrix
print(A) 

[[1 2 3 4 5]
 [2 0 0 0 0]
 [3 0 0 0 0]
 [4 0 0 0 0]
 [5 0 0 0 0]]


#Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [25]:
C = np.array ([[1,1,1,1,],[0,1,1,1,],[0,0,1,1,],[0,0,0,1],]) 
print()
print(C)


[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


#Question 3. Create a Python code that displays a square matrix which is symmetrical

In [23]:
#Create a symmetrical matrix
C = np.array([[1,2,3,4,5],[2,1,2,3,4],[3,2,1,2,3],[4,3,2,1,2],[5,4,3,2,1]])
print(C)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


#Question 4. What is the inverse of matrix C? Show your solution by python coding.

In [12]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #creation of matrix C
print(C)
print()
inv_C = np.linalg.inv(C) #creation of inverse matrix C
print(inv_C)

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


#Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding.

In [9]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(C)
print()
print(round(np.linalg.det(C))) #Determinant of given matrix in Question 4

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]

5


#Question 6. Find the roots of the linear equations by showing its python codes
5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [27]:
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
B = np.array([[[3.4],[8.8],[19.2]]])
C = np.linalg.inv(A) @ B #root of the equation
print(C)

[[[0.2]
  [0.4]
  [0.8]]]
