<a href="https://colab.research.google.com/github/roneljr/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector Space Operations

#Representing Vectors

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


##Describing Vectors in NumPy




In [3]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])
pool.shape
pool.ndim

2

In [6]:
U = np.array([[1,2,3],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
U = np.array([[1,2,3],[4,5,6]])
U.shape

(2, 3)

In [8]:
U = np.array([[1,2,3],[4,5,6]])
U.ndim

2

In [9]:
U = np.array([[1,2,3],[4,5,6]])
U
U.size

6

#Space

##Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations.

##Addition of Vectors

In [10]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
sum = addend1 + addend2
sum

array([1, 1, 0])

In [11]:
addend1 = np.array([0,0,0])
addend2 = np.array([1,1,0])
resultant = np.add(addend1,addend2)
resultant

array([1, 1, 0])

##Subtraction of Vector

In [12]:
#You will subtract the components of addend2 from addend1 : addend1-addend2
difference = addend1-addend2
difference

array([-1, -1,  0])

In [13]:
difference2 = np.subtract(addend1,addend2)
difference2 

array([-1, -1,  0])

##Scaling

In [14]:
A = np.array([1,5,8,9])
S = 5*A
S 

array([ 5, 25, 40, 45])

##Cross Product

In [15]:
A = np.array([2,3])
B = np.array([1,7])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

11


In [16]:
A = np.array([2,3,4])
B = np.array([1,7,1])

#Compute the cross product of A and B
cross = np.cross(A,B)
print(cross)

[-25   2  11]


In [17]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

#Compute the dot product of A and B

dot = np.dot(A,B)
print(dot)

23
