<a href="https://colab.research.google.com/github/roneljr/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix and Its Operations

In [1]:
#numpy
import numpy as np
A = np.array([[-5,0],[4,1]])
print(A)
print()
B = np.array([[6,-3],[2,3]])
print(B)
print()
print(A+B)
print()
print(B-A)
print()
print(A-B)

[[-5  0]
 [ 4  1]]

[[ 6 -3]
 [ 2  3]]

[[ 1 -3]
 [ 6  4]]

[[11 -3]
 [-2  2]]

[[-11   3]
 [  2  -2]]
